#In this project, you are going to work on the "Restaurant revenue" dataset which contains 100 observations of restaurants with 8 attributes.
Problem Statement:
Create a machine learning model to predict revenue of the restaurant based on
the features present in the dataset.
Dataset Attributes:
1. ID - Restaurant ID
2. Name - Name of the Restaurant
3. Franchise - Restaurant has franchise or not
4. Category - specific type of category provided by restaurant
5. No_of_item - Different types of items provided by restaurant
6. Order_Placed - Order placed by customer to restaurant (in lacs)
7. Revenue - Total amount of income generated by the restaurant
Tasks To Be Performed:
In this project, you have to predict the restaurant revenue based on the
independent features using a machine learning algorithm of your own choice.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [2]:
data = pd.read_csv(r"C:\Users\ACER\Downloads\revenue_prediction.csv")

In [3]:
data

,Id,Name,Franchise,Category,City,No_Of_Item,Order_Placed,Revenue
0,101,HungryHowie'sPizza,Yes,Mexican,Bengaluru,55,5.5,5953753
1,102,CharleysPhillySteaks,No,Varied Menu,Gurugram,72,6.8,7223131
2,103,Chuy's,Yes,Chicken,Pune,25,1.9,2555379
3,104,O'Charley's,Yes,Italian/Pizza,Mumbai,18,2.5,2175511
4,105,PolloTropical,Yes,Pizza,Noida,48,4.2,4816715
...,...,...,...,...,...,...,...,...
95,196,Wetzel'sPretzels,No,Italian/Pizza,Bengaluru,19,1.1,1270499
96,197,LaMadeleineCountryFrenchCafe,Yes,Varied Menu,Bengaluru,75,6.3,6412623
97,198,Giordano's,Yes,Varied Menu,Gurugram,77,6.2,6694797
98,199,IslandsFineBurgers&Drinks,Yes,Sports Bar,Pune,25,2.1,2344689
99,200,Mimi'sBistro&Bakery,No,BBQ,Mumbai,50,4.4,4567678

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            100 non-null    int64
 1   Name          100 non-null    object
 2   Franchise     100 non-null    object
 3   Category      100 non-null    object
 4   City          100 non-null    object
 5   No_Of_Item    100 non-null    int64
 6   Order_Placed  100 non-null    float64
 7   Revenue       100 non-null    int64
dtypes: float64(1), int64(3), object(4)
memory usage: 6.4+ KB

In [5]:
data.fillna(0, inplace=True)

In [6]:
label_encoder = LabelEncoder()
data['Franchise'] = label_encoder.fit_transform(data['Franchise'])
data['Category'] = label_encoder.fit_transform(data['Category'])

In [7]:
X = data[['Franchise', 'Category', 'No_Of_Item', 'Order_Placed']]
y = data['Revenue']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [9]:
y_pred = model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
rmse = mse ** 0.5
print("Root Mean Squared Error:", rmse)

Root Mean Squared Error: 565135.4458219808

In [11]:
new_restaurant_data = [[1, 3, 50, 2]]  
predicted_revenue = model.predict(new_restaurant_data)
print("Predicted Revenue for New Restaurant:", predicted_revenue)

Predicted Revenue for New Restaurant: [2599961.29]

C:\Users\ACER\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(